### ISSUE TITLE
bam files for noise

### ISSUE THREAD

**Issue by PHemarajata** [garcia-nacho/Precfinder#1]

**Comment by PHemarajata** [comment]
Where do I go to find the noise bam files? Thank you.

**Comment by garcia-nacho** [comment]
bam files are usually generated by the pipeline after mapping the reads to the reference genome.    
 You can obtain raw fastq  (and even bam files) at the [NCBI](https://www.ncbi.nlm.nih.gov/sra/?term=sars-cov-2) for example
